# Generated by Django 4.2.3 on 2023-11-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='working_status',
            field=models.BooleanField(default=False),
        ),
    ]
