# Generated by Django 4.2.3 on 2023-11-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_working_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='working_status',
            field=models.BooleanField(default=True),
        ),
    ]
