# Generated by Django 4.2 on 2023-04-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeowners',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
