# Generated by Django 4.1.7 on 2023-05-02 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_storeowners_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeowners',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='storeowners',
            name='token',
        ),
        migrations.AddField(
            model_name='storeowners',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeowners',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeowners',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeowners',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
