# Generated by Django 4.1.7 on 2023-06-01 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('WorkSchedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s_workschedule',
            options={'ordering': ['work_day', 'shift']},
        ),
        migrations.AlterField(
            model_name='s_workschedule',
            name='shift',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='s_workschedule',
            name='work_day',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=250)),
                ('start_day', models.DateTimeField(auto_now_add=True)),
                ('closing_date', models.DateTimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
    ]
