# Generated by Django 4.1.7 on 2023-06-10 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSchedule', '0003_remove_s_workschedule_store_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s_workschedule',
            options={},
        ),
        migrations.RemoveField(
            model_name='o_workschedule',
            name='store',
        ),
        migrations.RemoveField(
            model_name='o_workschedule',
            name='user',
        ),
        migrations.AddField(
            model_name='o_workschedule',
            name='staff_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='o_workschedule',
            name='week_day',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='o_workschedule',
            name='work_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WorkSchedule.workschedule'),
            preserve_default=False,
        ),
    ]
