# Generated by Django 4.1.7 on 2023-06-10 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkSchedule', '0004_alter_s_workschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_workschedule',
            name='s_work_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WorkSchedule.s_workschedule'),
            preserve_default=False,
        ),
    ]
