# Generated by Django 4.2.3 on 2023-09-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_code_item_image_link_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
