# Generated by Django 4.2.3 on 2023-09-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
