# Generated by Django 4.2.3 on 2023-09-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='category_id',
        ),
    ]
