# Generated by Django 4.2.3 on 2023-10-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_rename_category_item_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category_id',
            new_name='category',
        ),
    ]
