# Generated by Django 4.2.3 on 2023-11-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_rename_category_id_item_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='item',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_block'], name='items_item_is_bloc_0b67e9_idx'),
        ),
    ]
