# Generated by Django 4.2.3 on 2023-08-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to='store_images'),
        ),
    ]
