# Generated by Django 4.2.3 on 2023-08-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
